basePath: /v2
definitions:
  fr_internal_repository_models.Status:
    properties:
      id:
        type: integer
      text:
        example: status
        type: string
      time:
        type: string
    type: object
  internal_transport_http_v1.createNewsletterRequest:
    type: object
  internal_transport_http_v1.response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /newsletter/create:
    post:
      consumes:
      - application/json
      description: Создает рассылку
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          $ref: '#/definitions/internal_transport_http_v1.createNewsletterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_transport_http_v1.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_transport_http_v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_transport_http_v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_transport_http_v1.response'
      summary: CreateNewsletter
      tags:
      - Newsletter
swagger: "2.0"
